import type { Metadata } from "next";
import { Geist, Geist_Mono,Prosto_One,Orbitron,Raleway } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Navigation from "@/components/common/navigation";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//la police protos

const protos = Prosto_One({
  variable: "--font-protos",
  subsets: ["cyrillic"],
  weight:"400"
});
const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight:"600"
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight:"600"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${protos.variable} ${raleway.variable}  antialiased`}
      >
        <Navigation />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
